### ISSUE TITLE
enhancement: fix SearchView.test.tsx setup crash blocking UI integration tests

### ISSUE THREAD

**Issue by denhamparry** [denhamparry/djrequests#39]
## Enhancement Suggestion

Identified during code review of #36.

### Description

\`src/__tests__/SearchView.test.tsx\` currently fails at **setup** with:

\`\`\`
TypeError: localStorage.getItem is not a function
  at CookieStore.getCookieStoreIndex (msw/src/core/utils/cookieStore.ts:43:40)
\`\`\`

This is a pre-existing issue on \`main\` (not introduced by #36), likely a
compatibility gap between the installed MSW version and the jsdom
\`localStorage\` shim. Commit \`ef09120\` attempted a fix but the suite still
crashes before any test runs.

### Impact

- All UI integration tests are currently blocked from executing in CI.
- New tests (including the one added in #36 for the friendly outage
  message) are written but cannot verify behaviour until this is fixed.

### Rationale

Restore the UI integration suite so regressions in \`App.tsx\` /
\`useSongSearch\` get caught automatically rather than requiring manual
browser testing.

### Related

- Original issue: #36
- Commit \`ef09120\` (partial fix attempt)
- File: src/__tests__/SearchView.test.tsx

### Priority

Nice-to-have (non-blocking) — but functionally important for test
confidence.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
